# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaddt', models.DateTimeField(blank=True, null=True)),
                ('answerdt', models.DateTimeField(blank=True, null=True)),
                ('ipaddress', models.CharField(max_length=40)),
                ('useragent', models.TextField(blank=True, null=True)),
                ('nicetries', models.IntegerField()),
            ],
            options={
                'db_table': 'Access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('complexityid', models.AutoField(primary_key=True, serialize=False)),
                ('horizontalelements', models.IntegerField()),
                ('level', models.IntegerField()),
                ('verticalelements', models.IntegerField()),
                ('zone2points', models.IntegerField()),
            ],
            options={
                'db_table': 'Complexity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('languageid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Levelpoints',
            fields=[
                ('levelpointsid', models.AutoField(primary_key=True, serialize=False)),
                ('place1points', models.IntegerField(blank=True, null=True)),
                ('place2points', models.IntegerField(blank=True, null=True)),
                ('place3points', models.IntegerField(blank=True, null=True)),
                ('place4points', models.IntegerField(blank=True, null=True)),
                ('place5points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Levelpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('keyword', models.CharField(db_column='Keyword', max_length=50, primary_key=True, serialize=False)),
                ('russian', models.CharField(db_column='Russian', max_length=1000)),
                ('english', models.CharField(db_column='English', max_length=1000)),
                ('german', models.CharField(db_column='German', max_length=1000)),
                ('french', models.CharField(db_column='French', max_length=1000)),
            ],
            options={
                'db_table': 'Localization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('header', models.CharField(max_length=100)),
                ('img', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'News',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
                ('docnum', models.CharField(blank=True, max_length=100, null=True)),
                ('paydate', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zone2periodstart', models.DateField(blank=True, null=True)),
                ('zone2periodend', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('pictureid', models.AutoField(primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('picturedata', models.TextField()),
            ],
            options={
                'db_table': 'Pictures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('puzzleid', models.AutoField(primary_key=True, serialize=False)),
                ('puzzledata', models.TextField()),
                ('zone', models.IntegerField()),
                ('task', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('icon', models.TextField()),
            ],
            options={
                'db_table': 'Puzzles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('tournamentid', models.AutoField(primary_key=True, serialize=False)),
                ('startdatetime', models.DateTimeField()),
                ('tourpass', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prizepercent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notificationsent', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Tournaments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('userpass', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('billinginfo', models.TextField(blank=True, null=True)),
                ('zone2rating', models.IntegerField(blank=True, null=True)),
                ('zone3rating', models.IntegerField(blank=True, null=True)),
                ('sendnews', models.CharField(blank=True, max_length=1, null=True)),
                ('emailconfirmed', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
